# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: pankajroy
#   password: Pankajroy@01
#   host: localhost
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: portfolio_development

# test:
#   <<: *default
#   database: portfolio_test

# production:
#   <<: *default
#   database: portfolio_production
#   username: pankajroy
#   password: <%= Rails.application.credentials.dig(:database, :pg_password) %>


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= Rails.application.credentials.dig(:database, :username) || "pankajroy" %>
  password: <%= Rails.application.credentials.dig(:database, :password) || "Pankajroy@01" %>
  host: <%= Rails.application.credentials.dig(:database, :host) || "db" %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :development) || "portfolio_development" %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :test) || "portfolio_test" %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :production) || "portfolio_production" %>
  username: <%= Rails.application.credentials.dig(:database, :username) || "pankajroy" %>
  password: <%= Rails.application.credentials.dig(:database, :pg_password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>