# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: pankajroy
#   password: Pankajroy@01
#   host: localhost
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: portfolio_development

# test:
#   <<: *default
#   database: portfolio_test

# production:
#   <<: *default
#   database: portfolio_production
#   username: pankajroy
#   password: <%= Rails.application.credentials.dig(:database, :pg_password) %>


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "pankajroy") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "Pankajroy@01") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "portfolio_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "portfolio_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>